name: deploy-doc-to-github-pages
on:
  push:
    branches:
      - 'add-github-actions'
jobs:
  deploy-swagger-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.15'
      - run: echo "ğŸ§ Getting the project dependencies"
      - run: npm ci
      - run: echo "ğŸ§ Building and deploying the web to github pages"
      - run: npm run deploy