name: deploy-doc-to-github-pages
on:
  push:
    branches:
      - 'add-github-actions'
jobs:
  deploy-swagger-doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node 10.15
        uses: actions/setup-node@v2
        with:
          node-version: '10.15'
      - name: clean and install dependencies
        run: | 
          echo "ğŸ§ Getting the project dependencies"
          npm ci
      - name: build and deploy gh pages
        env:
          GH_TOKEN: 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
        run: | 
          echo "ğŸ§ Building and deploying the web to github pages"
          npm run deploy